# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My math title
email: math-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.27.1"         #Installing the remote theme required the jekyll-include-cache plugin
minimal_mistakes_skin: "dark"

# Site Settings:
locale: "en-US"
title: "Alette Wells Math Site"
title_separator: "-"
name: "Alette Wells"
description: "A collection of my research experience and interests, and blog posts."
url: "https://alette-wells.github.io"   # If you have trouble pushing the next commit, check this, and see if you need a base url -- MUST CHANGE IF HAVE DOMAIN NAME
logo: "/assets/images/mathsite_logo.png"
masthead_title: "Alette Wells"
enable_copy_code_button: true

atom_feed:
  hide: true

search: true
lunr: 
  search_within_pages: true

author:
  name: "Alette Wells"
  avatar: "/assets/images/Wells_Alette_2.png"
  bio: "Incoming PhD student at UChicago."
  links:
    - label: "alettew [at] uchicago [dot] edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alette-wells"


plugins:
  - jekyll-feed
  - jekyll-include-cache
# Let Jekyll see the pages in the _pages folder: 
include: 
- _pages                 # formerly written as ["_pages"]

# Defaults added for the minimal mistakes theme:
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false   
      share: true
      related: true
      show_date: true
  # _pages (folder yet to be set, does this mean the type parameter set below is meaningless?)
  - scope: 
      path: ""
      type: pages
    values: 
      layout: single
      author_profile: true





# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
